drop database sales;

CREATE database sales;

CREATE SCHEMA COHORT_ANALYSIS;
USE SCHEMA COHORT_ANALYSIS;

CREATE OR REPLACE TABLE RETAIL (
    Invoice varchar (10),
    StockCode varchar (20),
    Description varchar (200),
    Quantity number(8,2),
    InvoiceDate varchar(25),
    UnitPrice number(8,2),
    CustomerID number (10),
    Country varchar (25)
    );
    
    
select * from retail;

select count(*) from retail;  --541910

SELECT 
    COUNT(DISTINCT INVOICE) AS "UNIQUE INVOICE NUMBER"
    FROM RETAIL; --25900

SELECT DISTINCT COUNTRY FROM RETAIL;

SELECT COUNT(*)
    FROM RETAIL WHERE QUANTITY <=0;  -- NUMBER OF INVALID RECORD 10624

SELECT COUNT(*)
    FROM RETAIL WHERE INVOICE IS NULL;   -- NO MISSING VALUE IN INVOICE

SELECT COUNTRY,
        ROUND(SUM(QUANTITY*UNITPRICE),2) AS REVENUE
    FROM RETAIL
    WHERE QUANTITY >0 AND UNITPRICE >0
    GROUP BY COUNTRY
    ORDER BY REVENUE DESC;

SELECT COUNTRY,
        ROUND(SUM(QUANTITY*UNITPRICE),2) AS REVENUE
    FROM RETAIL
    WHERE QUANTITY >0 AND UNITPRICE >0
    GROUP BY COUNTRY
    HAVING REVENUE >=20000
    ORDER BY REVENUE DESC;
