SELECT * FROM ORDERS LIMIT 10;

SELECT
    O_CUSTKEY,
    ROUND(SUM(O_TOTALPRICE),0) AS REVENUE

FROM ORDERS
GROUP BY O_CUSTKEY
ORDER BY 2 DESC LIMIT 10;

SELECT * FROM CUSTOMER;

-- CUSKEY JAIGAI TAR NAME ANBO



SELECT
    O.O_CUSTKEY, C.C_NAME,
    ROUND(SUM(O_TOTALPRICE),0) AS REVENUE
FROM ORDERS AS O
    INNER JOIN CUSTOMER AS C ON O.O_CUSTKEY = C.C_CUSTKEY
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10;
--1 -> O.O_CUSTKEY, 2->C.C_NAME,3->REVENUE

--TOP 5 SELLING COUNTRY
SELECT
    O.O_CUSTKEY, N.N_NAME,
    ROUND(SUM(O_TOTALPRICE),0) AS REVENUE
FROM ORDERS AS O
    INNER JOIN CUSTOMER AS C ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN NATION AS N ON  C.C_CUSTKEY = N.N_NATIONKEY
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10;


--- WINDOW FUNCTION



SELECT
    O.O_CUSTKEY, N.N_NAME,
    ROUND(SUM(O_TOTALPRICE),0) AS REVENUE,
    RANK() OVER (ORDER BY ROUND(SUM(O_TOTALPRICE),0) DESC) AS NATION_RANK_BY_SALES
FROM ORDERS AS O
    INNER JOIN CUSTOMER AS C ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN NATION AS N ON C.C_NATIONKEY = N.N_NATIONKEY
GROUP BY 1,2
ORDER BY 3 DESC;

--SUB QUERY
SELECT *
FROM (SELECT
    O.O_CUSTKEY, N.N_NAME,
    ROUND(SUM(O_TOTALPRICE),0) AS REVENUE,
    RANK() OVER (ORDER BY ROUND(SUM(O_TOTALPRICE),0) DESC) AS NATION_RANK_BY_SALES
FROM ORDERS AS O
    INNER JOIN CUSTOMER AS C ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN NATION AS N ON C.C_NATIONKEY = N.N_NATIONKEY
GROUP BY 1,2
ORDER BY 3 DESC)

WHERE NATION_RANK_BY_SALES <=5;

--USING COMMON TABLE EXPRESSION (CTE)
WITH SALES_RANKING AS
(SELECT
    O.O_CUSTKEY, N.N_NAME,
    ROUND(SUM(O_TOTALPRICE),0) AS REVENUE,
    RANK() OVER (ORDER BY ROUND(SUM(O_TOTALPRICE),0) DESC) AS NATION_RANK_BY_SALES
FROM ORDERS AS O
    INNER JOIN CUSTOMER AS C ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN NATION AS N ON C.C_NATIONKEY = N.N_NATIONKEY
GROUP BY 1,2
ORDER BY 3 DESC)

SELECT *
FROM SALES_RANKING WHERE NATION_RANK_BY_SALES <= 5;
    




