select C_ACCTBAL from customer limit 5;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS LIMIT 10;

/*ONLY I WANT SPECIFIC COLUMN*/

SELECT O_TOTALPRICE, O_ORDERSTATUS, O_CUSTKEY FROM ORDERS LIMIT 10;


--RECORD

SELECT COUNT(*) FROM ORDERS;  --1500000


-- LIKE KOITA RESGION ACE DEKTE CHAI

SELECT DISTINCT O_ORDERSTATUS FROM ORDERS;
SELECT DISTINCT O_ORDERPRIORITY FROM ORDERS;

--UNIQUE CATASGOGY KOITA ACE JANTE CHAILE
SELECT COUNT (DISTINCT O_ORDERPRIORITY) FROM ORDERS; --5 TA

--COLUMM AR NAM DITE CHAILE
SELECT COUNT (DISTINCT O_ORDERPRIORITY) AS UNIQUE_ORDER_PRIORITY_CATAGORY FROM ORDERS
--OR
SELECT COUNT (DISTINCT O_ORDERPRIORITY) AS "UNIQUE ORDER PRIORITY CATAGORY" FROM ORDERS

--ORDER SUN
SELECT SUM(O_TOTALPRICE) AS "TOTAL REVENUR" FROM ORDERS;

--DOSOMIK KOM DEKAITE CHILE
SELECT ROUND(SUM(O_TOTALPRICE),1) AS "TOTAL REVENUR" FROM ORDERS;

--GROUP AR UNDER A REVINEW KOTO DEKTE CHAILE
SELECT O_ORDERPRIORITY, ROUND(SUM(O_TOTALPRICE),0) AS "TOTAL REVENUR" 
FROM ORDERS
GROUP BY O_ORDERPRIORITY;

--JODI SERIAL BY DEKTE CHAI
SELECT O_ORDERPRIORITY, ROUND(SUM(O_TOTALPRICE),0) AS "TOTAL REVENUR" 
FROM ORDERS
GROUP BY O_ORDERPRIORITY
ORDER BY O_ORDERPRIORITY;

--JODI REVENUE & HIGH REVENUE FIRST A RAKTE CHAILE
SELECT O_ORDERPRIORITY, ROUND(SUM(O_TOTALPRICE),0) AS "TOTAL REVENUR" 
FROM ORDERS
GROUP BY O_ORDERPRIORITY
ORDER BY "TOTAL REVENUR" DESC;
--OR- TOTAL REVENUE NA LIKE JEHETO 2 NO COLUMN TAI 2 LIKA JAI
SELECT O_ORDERPRIORITY, ROUND(SUM(O_TOTALPRICE),0) AS "TOTAL REVENUR" 
FROM ORDERS
GROUP BY O_ORDERPRIORITY
ORDER BY 2 DESC;

-- VIVA COMMON QUESTION WHERE AND HAVING DIFF.

SELECT O_ORDERPRIORITY, ROUND(SUM(O_TOTALPRICE),0) AS "TOTAL REVENUR" 
FROM ORDERS
WHERE O_ORDERSTATUS = 'F'
GROUP BY O_ORDERPRIORITY
ORDER BY 2 DESC;

--COMDITION AR SOMOI HAVING DITE HOI
SELECT O_ORDERPRIORITY, ROUND(SUM(O_TOTALPRICE),0) AS "TOTAL REVENUE" 
FROM ORDERS
WHERE O_ORDERSTATUS = 'F'
GROUP BY O_ORDERPRIORITY
HAVING "TOTAL REVENUE"  > 21987867088

--WHERE RAW DATA KE FILTERING KORE NIYE ASE
--HAVING AGREGITE RESULT UPOR FILTER KORE
ORDER BY 2 DESC;









